### ISSUE TITLE
Add selection option to Sidebar

### ISSUE THREAD

**Issue by siddhantprateek** [suvangipaul/Vibee#8]
- Use Material UI
 - add selection option to the sidebar
 
 - for Interest 
  > - Cycling
  > - Chess
  > - Football
    ..... 

 - Mode 
  > - Online
  > - Outdoor

![Screenshot 2022-03-26 001908](https://user-images.githubusercontent.com/43869046/160183264-887084ba-0878-477f-806c-1791a9211eb1.png)

**Comment by siddhantprateek** [comment]
Resources:
 - https://mui.com/components/selects/

**Comment by NikhitaBarat** [comment]
closed
